#!/bin/sh

# let me guess - you *need* more?
pkg_add -l installed

# enable battery managamenet and display manager
rcctl enable {apmd,xenodm}

# create default user with group memberships
password=$(encrypt -p)
useradd -m -G wheel,staff -p $password david

# move custom config files into /etc/
for config in $(find configs -type f | sed 's|configs/||g')
do
    cat "configs/${config}" > "/etc/${config}"
done

# don't update atime in files
sed -i 's/rw/rw,noatime,softdep/g' '/etc/fstab'

# create spool file for printer
doas mkdir '/var/spool/output/brother'
doas chown -R 'root:daemon' '/var/spool/output/brother'
chmod 770 '/var/spool/output/brother'
# create error log for printer
touch '/var/log/lpd-errors'
